# Generated by Django 4.2.20 on 2025-03-23 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='日记标题')),
                ('brief', models.CharField(max_length=64, verbose_name='日记摘要')),
                ('content', models.TextField(verbose_name='日记内容')),
                ('cover_img', models.ImageField(blank=True, default='default_cover.jpg', null=True, upload_to='diary_covers/', verbose_name='封面图')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='文章标题')),
                ('brief', models.CharField(blank=True, max_length=64, null=True, verbose_name='文章摘要')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('cover_img', models.ImageField(blank=True, default='default_cover.jpg', null=True, upload_to='diary_covers/', verbose_name='封面图')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_reprint', models.BooleanField(default=False, verbose_name='是否转载')),
                ('reprint_from', models.CharField(blank=True, max_length=64, null=True, verbose_name='转载源')),
                ('reprint_whom', models.CharField(blank=True, max_length=64, null=True, verbose_name='原作者')),
                ('tags', models.ManyToManyField(to='BackEnd.tag')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.AlterField(
            model_name='note',
            name='cover_img',
            field=models.ImageField(blank=True, default='default_cover.jpg', null=True, upload_to='diary_covers/', verbose_name='封面图'),
        ),
        migrations.CreateModel(
            name='EssayInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_count', models.IntegerField(default=0, verbose_name='被浏览次数')),
                ('liked_count', models.IntegerField(default=0, verbose_name='被赞次数')),
                ('disgusted_count', models.IntegerField(default=0, verbose_name='被踩次数')),
                ('encouraged_count', models.IntegerField(default=0, verbose_name='被鼓励次数')),
                ('essay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.essay')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
