# Generated by Django 4.2.20 on 2025-03-25 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0002_diary_essay_alter_note_cover_img_essayinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={},
        ),
        migrations.AlterModelOptions(
            name='essay',
            options={},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
        migrations.RemoveField(
            model_name='diary',
            name='brief',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='cover_img',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='is_show',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='modified_time',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='brief',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='cover_img',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='is_reprint',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='is_show',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='modified_time',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='reprint_from',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='reprint_whom',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='note',
            name='brief',
        ),
        migrations.RemoveField(
            model_name='note',
            name='cover_img',
        ),
        migrations.RemoveField(
            model_name='note',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='note',
            name='is_show',
        ),
        migrations.RemoveField(
            model_name='note',
            name='modified_time',
        ),
        migrations.RemoveField(
            model_name='note',
            name='second_classification',
        ),
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
        migrations.AlterField(
            model_name='diary',
            name='title',
            field=models.CharField(max_length=32, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='title',
            field=models.CharField(max_length=32, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=32, verbose_name='标题'),
        ),
        migrations.CreateModel(
            name='NoteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('brief', models.CharField(blank=True, max_length=64, null=True, verbose_name='摘要')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('cover_img', models.ImageField(blank=True, default='default_cover.jpg', null=True, upload_to='note_covers/', verbose_name='封面图')),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.note')),
                ('second_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.secondclassification')),
                ('tags', models.ManyToManyField(to='BackEnd.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EssayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('brief', models.CharField(blank=True, max_length=64, null=True, verbose_name='摘要')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('cover_img', models.ImageField(blank=True, default='default_cover.jpg', null=True, upload_to='essay_covers/', verbose_name='封面图')),
                ('is_reprint', models.BooleanField(default=False, verbose_name='是否转载')),
                ('reprint_source', models.CharField(blank=True, max_length=64, null=True, verbose_name='转载源')),
                ('reprint_author', models.CharField(blank=True, max_length=64, null=True, verbose_name='原作者')),
                ('essay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.essay')),
                ('tags', models.ManyToManyField(to='BackEnd.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiaryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('brief', models.CharField(blank=True, max_length=64, null=True, verbose_name='摘要')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('cover_img', models.ImageField(blank=True, default='default_cover.jpg', null=True, upload_to='diary_covers/', verbose_name='封面图')),
                ('diary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.diary')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiaryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_count', models.IntegerField(default=0, verbose_name='被浏览次数')),
                ('liked_count', models.IntegerField(default=0, verbose_name='被赞次数')),
                ('disgusted_count', models.IntegerField(default=0, verbose_name='被踩次数')),
                ('encouraged_count', models.IntegerField(default=0, verbose_name='被鼓励次数')),
                ('diary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.diary')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
