# Generated by Django 5.1.7 on 2025-04-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0002_bloginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='coffee_alipay',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='支付宝'),
        ),
        migrations.AddField(
            model_name='bloginfo',
            name='coffee_wechat',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='微信支付'),
        ),
        migrations.AddField(
            model_name='bloginfo',
            name='my_mail',
            field=models.EmailField(default='wangbo.pek@gmail.com', max_length=64, verbose_name='我的邮箱'),
        ),
        migrations.AddField(
            model_name='bloginfo',
            name='my_wechat',
            field=models.CharField(default='wboo1225', max_length=64, verbose_name='我的微信'),
        ),
    ]
