# Generated by Django 4.2.20 on 2025-03-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0003_alter_diary_options_alter_essay_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarylist',
            name='cover_img',
            field=models.ImageField(blank=True, default='default_cover.jpg', max_length=255, null=True, upload_to='diary_covers/', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='essaylist',
            name='cover_img',
            field=models.ImageField(blank=True, default='default_cover.jpg', max_length=255, null=True, upload_to='essay_covers/', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='notelist',
            name='cover_img',
            field=models.ImageField(blank=True, default='default_cover.jpg', max_length=255, null=True, upload_to='note_covers/', verbose_name='封面图'),
        ),
    ]
