# Generated by Django 5.1.7 on 2025-04-07 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0004_visitorlog_bloginfo_my_career_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloginfo',
            old_name='blog_article_count',
            new_name='blog_articles_count',
        ),
    ]
