# Generated by Django 4.2.20 on 2025-03-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0004_alter_diarylist_cover_img_alter_essaylist_cover_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarylist',
            name='cover_img',
            field=models.ImageField(blank=True, default='default_cover.jpg', max_length=512, null=True, upload_to='diary_covers/', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='essaylist',
            name='cover_img',
            field=models.ImageField(blank=True, default='default_cover.jpg', max_length=512, null=True, upload_to='essay_covers/', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='notelist',
            name='cover_img',
            field=models.ImageField(blank=True, default='default_cover.jpg', max_length=512, null=True, upload_to='note_covers/', verbose_name='封面图'),
        ),
    ]
