# Generated by Django 5.1.7 on 2025-04-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0005_rename_blog_article_count_bloginfo_blog_articles_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloginfo',
            old_name='coffee_alipay',
            new_name='coffee_by_alipay',
        ),
        migrations.RenameField(
            model_name='bloginfo',
            old_name='coffee_wechat',
            new_name='coffee_by_wechat',
        ),
    ]
