# Generated by Django 5.1.7 on 2025-04-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0006_rename_coffee_alipay_bloginfo_coffee_by_alipay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='blog_name',
            field=models.CharField(default='XiaoYi_Blog', max_length=64, verbose_name='博客名称'),
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='my_career',
            field=models.CharField(default='产品经理', max_length=64, verbose_name='我的职业'),
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='my_location',
            field=models.CharField(default='北京', max_length=64, verbose_name='我的所在地'),
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='my_name',
            field=models.CharField(default='Wang', max_length=64, verbose_name='我的名字'),
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='my_short_intro',
            field=models.CharField(default='', max_length=128, verbose_name='我的简短介绍'),
        ),
    ]
