# Generated by Django 4.2.20 on 2025-03-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0006_alter_diarylist_cover_img_alter_essaylist_cover_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essayinfo',
            name='essay',
        ),
        migrations.RemoveField(
            model_name='noteinfo',
            name='note',
        ),
        migrations.AddField(
            model_name='diarylist',
            name='disgusted_count',
            field=models.IntegerField(default=0, verbose_name='被踩次数'),
        ),
        migrations.AddField(
            model_name='diarylist',
            name='encouraged_count',
            field=models.IntegerField(default=0, verbose_name='被鼓励次数'),
        ),
        migrations.AddField(
            model_name='diarylist',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
        migrations.AddField(
            model_name='diarylist',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='是否推荐'),
        ),
        migrations.AddField(
            model_name='diarylist',
            name='liked_count',
            field=models.IntegerField(default=0, verbose_name='被赞次数'),
        ),
        migrations.AddField(
            model_name='diarylist',
            name='subtitle',
            field=models.CharField(default=2, max_length=32, verbose_name='副标题'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diarylist',
            name='viewed_count',
            field=models.IntegerField(default=0, verbose_name='被浏览次数'),
        ),
        migrations.AddField(
            model_name='essaylist',
            name='disgusted_count',
            field=models.IntegerField(default=0, verbose_name='被踩次数'),
        ),
        migrations.AddField(
            model_name='essaylist',
            name='encouraged_count',
            field=models.IntegerField(default=0, verbose_name='被鼓励次数'),
        ),
        migrations.AddField(
            model_name='essaylist',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
        migrations.AddField(
            model_name='essaylist',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='是否推荐'),
        ),
        migrations.AddField(
            model_name='essaylist',
            name='liked_count',
            field=models.IntegerField(default=0, verbose_name='被赞次数'),
        ),
        migrations.AddField(
            model_name='essaylist',
            name='subtitle',
            field=models.CharField(default=3, max_length=32, verbose_name='副标题'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='essaylist',
            name='viewed_count',
            field=models.IntegerField(default=0, verbose_name='被浏览次数'),
        ),
        migrations.AddField(
            model_name='notelist',
            name='disgusted_count',
            field=models.IntegerField(default=0, verbose_name='被踩次数'),
        ),
        migrations.AddField(
            model_name='notelist',
            name='encouraged_count',
            field=models.IntegerField(default=0, verbose_name='被鼓励次数'),
        ),
        migrations.AddField(
            model_name='notelist',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
        migrations.AddField(
            model_name='notelist',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='是否推荐'),
        ),
        migrations.AddField(
            model_name='notelist',
            name='liked_count',
            field=models.IntegerField(default=0, verbose_name='被赞次数'),
        ),
        migrations.AddField(
            model_name='notelist',
            name='subtitle',
            field=models.CharField(default=4, max_length=32, verbose_name='副标题'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notelist',
            name='viewed_count',
            field=models.IntegerField(default=0, verbose_name='被浏览次数'),
        ),
        migrations.AlterField(
            model_name='diarylist',
            name='brief',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='文本内容前64个字符'),
        ),
        migrations.AlterField(
            model_name='essaylist',
            name='brief',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='文本内容前64个字符'),
        ),
        migrations.AlterField(
            model_name='notelist',
            name='brief',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='文本内容前64个字符'),
        ),
        migrations.DeleteModel(
            name='DiaryInfo',
        ),
        migrations.DeleteModel(
            name='EssayInfo',
        ),
        migrations.DeleteModel(
            name='NoteInfo',
        ),
    ]
