# Generated by Django 4.2.20 on 2025-03-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0007_remove_essayinfo_essay_remove_noteinfo_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('img', models.ImageField(blank=True, max_length=128, null=True, upload_to='test_cover/')),
            ],
        ),
        migrations.AlterField(
            model_name='diarylist',
            name='brief',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='essaylist',
            name='brief',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='notelist',
            name='brief',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='摘要'),
        ),
    ]
