# Generated by Django 4.2.20 on 2025-03-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0009_delete_test_remove_diary_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarylist',
            name='brief',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='essaylist',
            name='brief',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='notelist',
            name='brief',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='摘要'),
        ),
    ]
