# Generated by Django 4.2.20 on 2025-03-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0010_alter_diarylist_brief_alter_essaylist_brief_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notelist',
            name='cover_img',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='封面图'),
        ),
    ]
