# Generated by Django 5.1.7 on 2025-03-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0012_alter_notelist_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notelist',
            name='cover_img',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='封面图'),
        ),
    ]
