# Generated by Django 5.1.7 on 2025-03-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0014_remove_essaylist_essay_remove_essaylist_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='html_content',
        ),
        migrations.AddField(
            model_name='note',
            name='table_of_content',
            field=models.TextField(blank=True, null=True, verbose_name='文章目录'),
        ),
    ]
