# Generated by Django 5.1.7 on 2025-04-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0015_remove_note_html_content_note_table_of_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='html_content',
        ),
        migrations.RemoveField(
            model_name='diarylist',
            name='viewed_count',
        ),
        migrations.RemoveField(
            model_name='note',
            name='table_of_content',
        ),
        migrations.AddField(
            model_name='diarylist',
            name='motion',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='心情'),
        ),
    ]
