# Generated by Django 5.1.7 on 2025-04-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0016_remove_diary_html_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='title',
            field=models.CharField(max_length=64, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='diarylist',
            name='title',
            field=models.CharField(max_length=64, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=64, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='notelist',
            name='title',
            field=models.CharField(max_length=64, verbose_name='标题'),
        ),
    ]
