<template>
    <div>1home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>homex</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home</div>
    <div>home2</div>
</template>

<script setup lang='ts'>
    defineOptions({
        name: 'Home',
        inheritAttrs: false
    })
</script>

<style scoped lang='scss'>

</style>